version: '3'
services: 
    rabbitmq:
        image: rabbitmq:management 
        container_name: rabbitmq
        ports: 
            - 5672:5672
            - 15672:15672
        restart: always
    
    sender:
        build: sender/
        restart: always
        environment: 
            - QUEUE_NAME=test-queue
        ports: 
            - 80:3000
        depends_on: 
            - rabbitmq
    
    receiver_01:
        build: receiver/
        container_name: receiver_01
        restart: on-failure
        environment: 
            - QUEUE_NAME=${QUEUE_NAME}
            - TZ=Asia/Bankok
        depends_on: 
            - rabbitmq

    receiver_02:
        build: receiver/
        container_name: receiver_02
        restart: on-failure
        environment: 
            - QUEUE_NAME=${QUEUE_NAME}
            - TZ=Asia/Bankok
        depends_on: 
            - rabbitmq
    
    receiver_03:
        build: receiver/
        container_name: receiver_03
        restart: on-failure
        environment: 
            - QUEUE_NAME=${QUEUE_NAME}
            - TZ=Asia/Bangkok
        depends_on: 
            - rabbitmq
        